/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProRouteImport } from './routes/pro'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProIndexRouteImport } from './routes/pro.index'
import { Route as ProviderIdRouteImport } from './routes/provider.$id'
import { Route as ProServicosRouteImport } from './routes/pro.servicos'
import { Route as ProHorariosRouteImport } from './routes/pro.horarios'
import { Route as ProHistoricoRouteImport } from './routes/pro.historico'
import { Route as ProEstabelecimentoRouteImport } from './routes/pro.estabelecimento'
import { Route as ProAgendaRouteImport } from './routes/pro.agenda'
import { Route as BookProviderIdServiceIdRouteImport } from './routes/book.$providerId.$serviceId'

const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIndexRoute = ProIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProRoute,
} as any)
const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProServicosRoute = ProServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => ProRoute,
} as any)
const ProHorariosRoute = ProHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => ProRoute,
} as any)
const ProHistoricoRoute = ProHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => ProRoute,
} as any)
const ProEstabelecimentoRoute = ProEstabelecimentoRouteImport.update({
  id: '/estabelecimento',
  path: '/estabelecimento',
  getParentRoute: () => ProRoute,
} as any)
const ProAgendaRoute = ProAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ProRoute,
} as any)
const BookProviderIdServiceIdRoute = BookProviderIdServiceIdRouteImport.update({
  id: '/book/$providerId/$serviceId',
  path: '/book/$providerId/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/perfil': typeof PerfilRoute
  '/pro': typeof ProRouteWithChildren
  '/pro/agenda': typeof ProAgendaRoute
  '/pro/estabelecimento': typeof ProEstabelecimentoRoute
  '/pro/historico': typeof ProHistoricoRoute
  '/pro/horarios': typeof ProHorariosRoute
  '/pro/servicos': typeof ProServicosRoute
  '/provider/$id': typeof ProviderIdRoute
  '/pro/': typeof ProIndexRoute
  '/book/$providerId/$serviceId': typeof BookProviderIdServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/perfil': typeof PerfilRoute
  '/pro/agenda': typeof ProAgendaRoute
  '/pro/estabelecimento': typeof ProEstabelecimentoRoute
  '/pro/historico': typeof ProHistoricoRoute
  '/pro/horarios': typeof ProHorariosRoute
  '/pro/servicos': typeof ProServicosRoute
  '/provider/$id': typeof ProviderIdRoute
  '/pro': typeof ProIndexRoute
  '/book/$providerId/$serviceId': typeof BookProviderIdServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/perfil': typeof PerfilRoute
  '/pro': typeof ProRouteWithChildren
  '/pro/agenda': typeof ProAgendaRoute
  '/pro/estabelecimento': typeof ProEstabelecimentoRoute
  '/pro/historico': typeof ProHistoricoRoute
  '/pro/horarios': typeof ProHorariosRoute
  '/pro/servicos': typeof ProServicosRoute
  '/provider/$id': typeof ProviderIdRoute
  '/pro/': typeof ProIndexRoute
  '/book/$providerId/$serviceId': typeof BookProviderIdServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/perfil'
    | '/pro'
    | '/pro/agenda'
    | '/pro/estabelecimento'
    | '/pro/historico'
    | '/pro/horarios'
    | '/pro/servicos'
    | '/provider/$id'
    | '/pro/'
    | '/book/$providerId/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auth'
    | '/perfil'
    | '/pro/agenda'
    | '/pro/estabelecimento'
    | '/pro/historico'
    | '/pro/horarios'
    | '/pro/servicos'
    | '/provider/$id'
    | '/pro'
    | '/book/$providerId/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/auth'
    | '/perfil'
    | '/pro'
    | '/pro/agenda'
    | '/pro/estabelecimento'
    | '/pro/historico'
    | '/pro/horarios'
    | '/pro/servicos'
    | '/provider/$id'
    | '/pro/'
    | '/book/$providerId/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  PerfilRoute: typeof PerfilRoute
  ProRoute: typeof ProRouteWithChildren
  ProviderIdRoute: typeof ProviderIdRoute
  BookProviderIdServiceIdRoute: typeof BookProviderIdServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/': {
      id: '/pro/'
      path: '/'
      fullPath: '/pro/'
      preLoaderRoute: typeof ProIndexRouteImport
      parentRoute: typeof ProRoute
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/servicos': {
      id: '/pro/servicos'
      path: '/servicos'
      fullPath: '/pro/servicos'
      preLoaderRoute: typeof ProServicosRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/horarios': {
      id: '/pro/horarios'
      path: '/horarios'
      fullPath: '/pro/horarios'
      preLoaderRoute: typeof ProHorariosRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/historico': {
      id: '/pro/historico'
      path: '/historico'
      fullPath: '/pro/historico'
      preLoaderRoute: typeof ProHistoricoRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/estabelecimento': {
      id: '/pro/estabelecimento'
      path: '/estabelecimento'
      fullPath: '/pro/estabelecimento'
      preLoaderRoute: typeof ProEstabelecimentoRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/agenda': {
      id: '/pro/agenda'
      path: '/agenda'
      fullPath: '/pro/agenda'
      preLoaderRoute: typeof ProAgendaRouteImport
      parentRoute: typeof ProRoute
    }
    '/book/$providerId/$serviceId': {
      id: '/book/$providerId/$serviceId'
      path: '/book/$providerId/$serviceId'
      fullPath: '/book/$providerId/$serviceId'
      preLoaderRoute: typeof BookProviderIdServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProRouteChildren {
  ProAgendaRoute: typeof ProAgendaRoute
  ProEstabelecimentoRoute: typeof ProEstabelecimentoRoute
  ProHistoricoRoute: typeof ProHistoricoRoute
  ProHorariosRoute: typeof ProHorariosRoute
  ProServicosRoute: typeof ProServicosRoute
  ProIndexRoute: typeof ProIndexRoute
}

const ProRouteChildren: ProRouteChildren = {
  ProAgendaRoute: ProAgendaRoute,
  ProEstabelecimentoRoute: ProEstabelecimentoRoute,
  ProHistoricoRoute: ProHistoricoRoute,
  ProHorariosRoute: ProHorariosRoute,
  ProServicosRoute: ProServicosRoute,
  ProIndexRoute: ProIndexRoute,
}

const ProRouteWithChildren = ProRoute._addFileChildren(ProRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  PerfilRoute: PerfilRoute,
  ProRoute: ProRouteWithChildren,
  ProviderIdRoute: ProviderIdRoute,
  BookProviderIdServiceIdRoute: BookProviderIdServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
